name: Notify Vercel Server

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch
  workflow_dispatch:  # Allows you to trigger manually from the GitHub Actions interface

jobs:
  notify_vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Call Vercel-deployed Node.js API
        run: |
          curl -X POST ${{ secrets.VERCEL_API_URL }}/vercel-deploy-hook \
          -H "Content-Type: application/json" \
          -d '{
              "payload": {
                "name": "My Project",
                "target": "production",
                "gitSource": {
                  "ref": "${{ github.ref_name }}",
                  "message": "${{ github.event.head_commit.message }}"
                },
                "createdAt": "${{ github.event.head_commit.timestamp }}"
              }
            }'
